# Pandas Tutorial
Tutorial5 link: https://youtu.be/QUClKFFn1Vk?si=ra1etaU7l_8M8iFn

Pandas is open source, BSD=licensed library providing high-performance, easy-to-use data structures and data analysis tools for Python programming language.

#### Agenda

- What is Data Frames?
- What is Data Series>
- Different operation in Pandas

### Inbuilt Functions in Pandas
- df = pd.DataFrame(...)  # for creating the dataFrame
- df.head()
- df.loc('Row1')
- df.iloc[:,:]
- df.isnull().sum() 
- df['Column1'].value_counts()
- df['Column1'].unique()
- df.values
- df = pd.read_csv(StringIO(data), usecols=['col1','col3'])
- df.dtypes
- pd.read_csv(StringIO(data), index_col=0)
- df.info()
- df.describe()

### Pandas Part 1

In [1]:
## First import numpy and pandas
import pandas as pd
import numpy as np

In [2]:
## Playing with Dataframe
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1','Row2','Row3','Row4','Row5'], columns=['Column1','Column2','Column3','Column4'])

In [3]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [4]:
df.to_csv('Test1.csv')

In [5]:
## Accessing the elements
### 1. .loc  2. .iloc
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [6]:
type(df.loc['Row1'])

pandas.core.series.Series

In [7]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
type(df.iloc[:,:])

pandas.core.frame.DataFrame

In [9]:
df.iloc[0:2,0:2]

Column1  Column2
Row1        0        1
Row2        4        5

In [10]:
df.iloc[0:2,0:1]

Column1
Row1        0
Row2        4

In [11]:
type(df.iloc[0:2,0:1]) # still taking as a dataframe because row and column name also has a representation.

pandas.core.frame.DataFrame

In [12]:
print(df.iloc[0:2,0]) # here taking a single column, we can oberserve difference in visual representation.
type(df.iloc[0:2,0])

Row1    0
Row2    4
Name: Column1, dtype: int64


pandas.core.series.Series

In [13]:
# Convert Dataframes into array
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
type(df.iloc[:,:].values)

numpy.ndarray

In [15]:
df.iloc[:,:].values.shape

(5, 4)

In [16]:
df.isnull().sum() # to check the total null values in each column

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [17]:
df['Column1'].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [18]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [19]:
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int64

In [20]:
df[['Column1','Column3']]

Column1  Column3
Row1        0        2
Row2        4        6
Row3        8       10
Row4       12       14
Row5       16       18

In [21]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Pandas Part 2

In [22]:
df = pd.read_csv('mercedesbenz.csv')

In [23]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [26]:
df.describe() # When we are using .describe only int and float columns are taken into consideration, not a categoral column because we can not find mean and other mathematical values of it.

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [28]:
# Get the unique category count
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [29]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

### CSV

In [36]:
from io import StringIO, BytesIO

In [86]:
data = ('col1,col2,col3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3')

In [87]:
type(data)

str

In [88]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [89]:
## Read from specific columns
df = pd.read_csv(StringIO(data), usecols=['col1','col3'])

In [90]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [91]:
df.to_csv('Test2.csv')

In [92]:
df.dtypes

col1    object
col3     int64
dtype: object

In [93]:
# Index columns and training delimiters
data = ('index,a,b,c\n'
       '4,apple,bat,5.7\n'
       '8,orange,cow,10')

In [94]:
pd.read_csv(StringIO(data))

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [95]:
pd.read_csv(StringIO(data), index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [96]:
data = ('a,b,c\n'
       '4,apple,bat,\n'
       '8,orange,cow,')

In [97]:
pd.read_csv(StringIO(data))

a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [98]:
pd.read_csv(StringIO(data), index_col=False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [99]:
pd.read_csv(StringIO(data), usecols=['b','c'], index_col=False)

b    c
0   apple  bat
1  orange  cow

In [100]:
## Quoting and Escape Characters. Very Useful in NLP
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [101]:
pd.read_csv(StringIO(data), escapechar="\\")

a  b
0  hello, "Bob", nice to see you  5

In [102]:
## URL to CSV
df = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item', sep='\t')

HTTPError: HTTP Error 403: Forbidden